# Generated by Django 4.0.2 on 2022-03-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstablishmentName', models.CharField(max_length=255)),
                ('EstablishmentStatus', models.CharField(max_length=10)),
                ('OpenDate', models.DateField()),
                ('CloseDate', models.DateField()),
                ('Town', models.CharField(default='London', max_length=64)),
                ('Postcode', models.CharField(default=None, max_length=5)),
                ('SchoolWebsite', models.CharField(default=None, max_length=255)),
                ('TelephoneNum', models.CharField(default=None, max_length=15)),
            ],
        ),
    ]
